name: Newth

on: push

jobs:
  Autotools:
    name: Autotools Tarball
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Autotools Project Environment
        working-directory: Autotool
        run: |
          export FAKETIME=$(TZ=UTC0 git show --quiet --date='format-local:%Y%m%d%H%M%S' --format="%cd")
          mv autoconf.ac configure.ac
          sed -i "s/\(AC_INIT(\[Newth\],\)\[0\]/\1[$FAKETIME]/" configure.ac
          ln -s ../src 
          ln -s ../test
          rm *.md

      - name: Install Autotools & Project Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf autoconf-archive automake gcc libreadline8t64 libreadline-dev libtool make pkg-config

      - name: Run Autotools
        working-directory: Autotool
        run: |
          autoreconf -fi

      - name: Configure Project
        working-directory: Autotool
        run: |
          ./configure

      - name: Distribute Project
        working-directory: Autotool
        run: |
          make distcheck

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 'Autotools'
          path: |
            Autotool/newth-*.tar.*
          compression-level: 0